### ISSUE TITLE
No support for Ubuntu server

### ISSUE THREAD

**Issue by lisuml** [rentabiliweb/puppet-supervisor#1]
I'm getting this error:

Error: Could not find template 'supervisor/sysconfig.Ubuntu.erb' at /etc/puppet/modules/supervisor/manifests/init.pp:92 on node dmlis-web.modeva.local

And actually there is no template named sysconfig.Ubuntu.erb in templates/ dir.

**Comment by rockyluke** [comment]
It's a mistake and it's solved in the last commit.
