### ISSUE TITLE
Error when trying to start supervisord

### ISSUE THREAD

**Issue by greg0ire** [rentabiliweb/puppet-supervisor#2]
> sudo /etc/init.d/supervisor restart
Restarting supervisor: Error: invalid literal for int() with base 8: '18'
For help, use /usr/bin/supervisord -h

There is something fishy in the configuration file : 

> grep -rn 18 /etc/supervisor/
/etc/supervisor/conf.d/03-supervisord.conf:10:umask=18

**Comment by rockyluke** [comment]
Did you change the 'supervisord_umask' parameters ? Actually, the default value is : $supervisord_umask = 022.

Can you give me more information ? (module version, configuration, etc.) :)

**Comment by greg0ire** [comment]
Sadly, I was in a hurry and decided to switch to another module to get things working. I did not change this parameter, and I changed very few of them all. I don't remember the version, but I guess it must be the latest (I installed the module with `puppet module install`). The machine is an Ubuntu 14.04 machine.

**Comment by rockyluke** [comment]
We've tested it on Ubuntu 14.04 and didn't see any issue, the default value is 022 :(

**Comment by greg0ire** [comment]
Okay guess my setup must have something particular…

**Comment by AdamJacobMuller** [comment]
I just ran into this exact issue, it was caused by the fact that I am using the future parser which I would guess @greg0ire is also using.

In specific, you need to quote these:
>   $supervisord_umask            = "022",
>   $unix_http_server_chmod       = "0700",

**Comment by greg0ire** [comment]
Good guess!

**Comment by rockyluke** [comment]
Okay, I've fixed my mistake. Thanks a lot !
