### ISSUE TITLE
service don't start: Error: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by daks** [rentabiliweb/puppet-supervisor#4]
Hello,

I'm trying to use this module to manage some supervisord configuration. I installed version 1.1.5 and wrote a manifest like this:

    class { 'supervisor': }
    supervisor::program { 'carbon-relay-ng':
        program_command => '/home/carbon-relay-ng/carbon-relay-ng /etc/carbon-relay-ng/carbon-relay-ng.ini',
        program_process_name    => 'carbon-relay-ng',
        program_user    => 'carbon-relay-ng',
    }

When starting the supervisor service, I have the following error message

    Restarting supervisor: Error: invalid literal for int() with base 10: ''

The generated program configuration looks like this (removing commented lines)

    [program:carbon-relay-ng]
    command=/home/carbon-relay-ng/carbon-relay-ng /etc/carbon-relay-ng/carbon-relay-ng.ini
    process_name=carbon-relay-ng
    autostart=true
    autorestart=true
    startsecs=5
    stopwaitsecs=10
    user=carbon-relay-ng
    stdout_logfile=/var/log/supervisor/carbon-relay-ng.log
    stderr_logfile=/var/log/supervisor/carbon-relay-ng.err
    stderr_logfile_maxbytes=
    stderr_logfile_backups=
    stderr_capture_maxbytes=
    stderr_events_enabled=

If I comment out the 4 last lines (those with empty values), the service starts. I think it means that I need to provide values to those directives.
I didn't saw in documentation that I need to provide values and puppet execution didn't raise any error/warning.

Do you think the module should provide default values for these directives?
Or remove them from the generated program configuration?
Or update doc to indicate it?

Thanks

**Comment by rockyluke** [comment]
It was a mistake in program.pp. It's solved in the last commit and pushed on the forge.

My apologies for this issue, can you please upgrade your module (1.1.6) ?

Thanks a lot for your very complete report !!

**Comment by daks** [comment]
Fixed in fact with version 1.1.6. Thanks for your reactivity :)

**Comment by rockyluke** [comment]
My pleasure. Thanks again for your report.
